### ISSUE TITLE
Can I use PHP-Websockets tree legacy? 

### ISSUE THREAD

**Issue by petrospap** [ghedipunk/PHP-Websockets#111]
Hello 
I try to connect with wss
I see this legacy
https://github.com/ghedipunk/PHP-Websockets/tree/legacy
My question is, can I use this or is not working.

**Comment by petrospap** [comment]
Seems like is a long road to make it work
I need some simple help here
1 can anyone confirm that this legacy is working?
2 has anyone tried on xampp/localhost to make it work?
3 I assume that ciphers not need any changes?
Thank you

**Comment by Will-Long** [comment]
Why would you want to use the legacy over this one? That being said. 
1.) It's not at least not if your using xampp with php 5.6
2.) Yes more trouble than its worth when this library works. That being said the only problem I saw with it is technically the handshake method (Doesn't read properly from the socket)
3.)No the ciphers don't need any changing if you wanted to use it.

**Comment by petrospap** [comment]
I drop this, mod_proxy does the trick
Thanks
