### ISSUE TITLE
How to disconnect user if internet connection is not available

### ISSUE THREAD

**Issue by renznamoc21** [ghedipunk/PHP-Websockets#116]
Hi.

How can i disconnect user if the internet connection change to none?

socket.close();
socket = null;

works manually and CLI logs Client disconnected

but when those codes called in offline event it doesn't logs any in CLI  

Thank you

**Comment by renznamoc21** [comment]
I still cant trace the code called when the connection lost(sudden internet loss, changes of network connection)

**Comment by ghedipunk** [comment]
If a person is disconnected due to a network issue, the abstract function Websockets::closed will be run by Websockets::disconnect.

You are required to implement the closed() method.  You are invited to override the disconnect() method if you need to know the particular reason why a given connection is closed.

And I am embarassed that I set it up this way originally.

**Comment by renznamoc21** [comment]
It seems like the Websockets::disconnect does not called when a person is diconnected due to network issue, im running this using php 7 codeigniter framework and ubutu server, to recreate the network issue, i did disable my Ethernet adopter in network settings

**Comment by youssefali424** [comment]
what was the error that you got? in the server

**Comment by renznamoc21** [comment]
There is no any logs in server CLI nor any error  at the time i disconnect/disabled  my network

**Comment by renznamoc21** [comment]
Here's the screen shot of server cli logs 
https://ibb.co/mzwHyU
the the screen shot of browser in mobile after i turned off my wifi
https://ibb.co/b6MjdU
it says disconnected - status 3 but the server does not recognized it 


please help me thank you

**Comment by youssefali424** [comment]
https://ibb.co/c2oZDU 
so basically i just tried the raw server(i changed it alot for my needs before and i didnt work on it since two years ago) and it notices it as i said before and you can change the function to do whatever you want when disconnected

**Comment by youssefali424** [comment]
i dont understand how you didnt notice the function its so direct they called it disconnect and you will see that the client get disconnected and deleted from users list in it as well(as i said before)

**Comment by renznamoc21** [comment]
Yes disconnected works perfectly to me on close of browser/ browser's tab but while im connected then turn of my wifi disconnect function does not called i dont know why disconnect does not call when wifi is off, just like how disconnect call when browser/tab is closed

**Comment by Xaraknid** [comment]
I can explain what happens.

1- When you use "quit", you close normaly the websocket connection.
2- When you close the browser, you close abruptly the websocket connection.
3- When you unplug ethernet cable ( or wifi connection ), the websocket stay open.

It's the force of TCP if you plug back ( or reconnect wifi ) quick enought and have the same IP. The data will flow back on the last thing you receive.

So after some unresponse from client ( no ACK ) or the timeout on TCP occur the connection will be terminated.

**Comment by renznamoc21** [comment]
Thank you very much @Xaraknid , @ghedipunk , @youssefali424 
for your help
Question:
It is safe to do that the client send ping to server every sec. to log the last time activity of user then in server checking all connected user last time activity if > 5sec user will be disconnected?

**Comment by Xaraknid** [comment]
All depend what you need.

You should use server side to send PING, all official current browser send Automaticaly the PONG.

Keep in consideration lag spike, loss packet, bandwidth, stress time, ect. Data is send/receive sequentially that mean if you send a huge message that take time your PING will be received after that.

So 5 sec you have a fair chance to disconnect a valid connection. 

I suggest you let the OS deal mostly with that. Sure a Ping/Pong exchange is just 4 bytes but it add up quickly for something that should happens rarely. With 100 clients you ping every 5 secs you'll end up with 288 Kbytes/hour that didn't count the CPU usage to fill and unfill the list.

You should check every X (higher than TIMEOUT) minutes that will not stress unecessary the server.  Also make sure to remove from the list the disconnected that happens between every check.

**Comment by renznamoc21** [comment]
Any idea how to do this server side ping and how server manage the pong of client ?

**Comment by youssefali424** [comment]
the easy way send a specific message(num or word.....etc) then the client should replay if the ack didnt come then he is disconnected for sure you have to implement it in client and server side(make a timer to know idle users like if there is no traffic or data sent to server send the ack )

**Comment by youssefali424** [comment]
or you can depend on the browser for the bong like check the browser response as Xaraknid said but you need to know how the browser respond

**Comment by renznamoc21** [comment]
Thank you very much guys
