### ISSUE TITLE
SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally

### ISSUE THREAD

**Issue by mkeryeski** [ghedipunk/PHP-Websockets#19]
I am using the echo test server with a few modiciations, which is working properly in Firefox and Chrome. However, after about 30 seconds I get this error in IE console:

SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally

And the client then disconnects.

Any ideas?

**Comment by NithishHemanth** [comment]
Hi All, 

I also face the same error in my server having signalr2.2.2 and websocket protocol enabled for my web application.

[11:14:06 GMT-0600 (Central Standard Time)] SignalR: Connecting to websocket endpoint 'wss://xx/xx/signalr/reconnect?transport=webSockets&groupsToken=xxx
[11:14:06 GMT-0600 (Central Standard Time)] SignalR: Websocket opened.
SignalR state changed from: reconnecting to: connected
id_1516900245702 is reconnected
SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally

Any thoughts to resolve this issue would be more helpful.

thanks!

**Comment by NithishHemanth** [comment]
Any thoughts on this issue?

**Comment by ghedipunk** [comment]
My thoughts are: This isn't enough information to go on (and really deserves its own thread, since the original thread was for an issue staying connected to IE, not an issue with SignalR).

**Comment by DetectiveBox** [comment]
Hi,
 I face the same error on IE Edge , and it does not occur always but occasionally. I have inport polyfill for ts. How did you solve this error please?

**Comment by gfox1984** [comment]
This is very empirical, but I seem to reproduce the problem on Edge only when the payload I'm sending to the server is approximately 60K or greater.

**Comment by gfox1984** [comment]
Correction: for the guys who use signalr, there's a setting to change to allow messages bigger than 64K.
Just drop this line in your Startup.cs, after app.MapSignalR():

`Microsoft.AspNet.SignalR.GlobalHost.Configuration.MaxIncomingWebSocketMessageSize = null;`
