### ISSUE TITLE
Socket error: Connection reset by peer, when Nmap

### ISSUE THREAD

**Issue by guillaumeinnov24** [ghedipunk/PHP-Websockets#21]
(great job btw!)
I'm still on the example. Launching testwebsock.php works fine, but asa a nmap scan occured, a RST packet is received and the connection fail fatally. Dropping data.

Server started
Listening on: 0.0.0.0:9000
Master socket: Resource id #6
Client connected. Resource id #7
>> Socket error: Connection reset by peer

>> nmap 192.168.0.10 -p9000

**Comment by ghedipunk** [comment]
Unusual client disconnects (or any socket error, for that matter) no longer throw an exception.
