### ISSUE TITLE
The web socket cannot be closed by client

### ISSUE THREAD

**Issue by jxngai** [ghedipunk/PHP-Websockets#36]
At the client side if I try to close the web socket. it does not close immediately. There is a bug in websocket.php

Instead of

    if ($user->hasSentClose)
    {
         $this->disconnect($user);
    }

It should be

    if ($user->hasSentClose)
    {
         $this->disconnect($user->socket);
    }

**Comment by hopeseekr** [comment]
+1 The fix worked for me.
