### ISSUE TITLE
New feature discussion: Pre-frame bulk messages

### ISSUE THREAD

**Issue by ghedipunk** [ghedipunk/PHP-Websockets#43]
Framing a message is a time consuming operation.  If there are multiple messages with the same contents, frame them once.

(Maybe make a message class?  Definitely going to do for the next version...  not sure if we'll implement it like that on the legacy branch, since it bends the paradigm too far.)

**Comment by ghedipunk** [comment]
After thinking, it's probably best to split messages out into a new class on the legacy branch, because there are some very valid use cases for having different message object types...  for example, in the same server, a person could have chat messages and have messages that frame HTML updates on the page.  

Also, important for other development going on, there should also be TLS messages, which also get encrypted and framed within the TLS protocols.

It fits within the legacy paradigm in the same way that having a user class fits in.

**Comment by Xaraknid** [comment]
master branch : the frame() have link with user class that why you can't frame() once before sending to multiple client.

In development branch it allready able to frame() once and send to multiple client.  I remove the user class link within frame() by doing this I can still send to one client at time after framing the message, or framing the message once and broadcast it

There is two method for outgoing data : send() (single client) and broadcast() (multiple client ).

The data you send is irrelevant to the method use ( message / html / binary ) as long the data is exactly the same for multiple client we should frame it once.

Unless I miss something on the RFC both ws and wss MUST mask data prior to sending it. Unless it different the messages didn't need a proper class. Message / frame are userfree.

The layer process of data in outgoing:
ws : data -> framing -> mask -> send
wss : data-> framing -> mask -> encrypt -> send

As encrypt is per user it's when you encrypt it that the road split.  The data is the same untill that.

**Comment by ghedipunk** [comment]
That's exactly why I'm thinking of adding a message class.

    $recipients = array($user1, $user2, $user3, [...]);
    $msg = new Message('This is a message.', $recipients);
    $msg->addRecipient($userX);
    $msg->send();

    ...

    class Message implements \Phpws\Interfaces\Message
    {
        function __construct($text = '', \Phpws\Core\WebSocketUser $recipients = array()) {...}
        public function addRecipient(\Phpws\Core\WebSocketUser $recipient) {...}
        public function addRecipients(array $recipients) {...}
        public function removeRecipient(\Phpws\Core\WebSocketUser $recipient) {...}
        public function setMessage($message) {...}
        public function send() {...} // adds self to server's message queue.
        public function getRecipients() {...}
        public function getSendStatus() {...} // could be unsent, sent to some, or sent to all.
        protected function frame($message) {...}
        protected function tls_frame($message, $recipient) {...}
    }

Then someone implementing messages that need additional structures on the message (i.e., wants to differentiate between HTTP content for updating elements on the page v. updating contents of a chat window) can then extend the base Message class...

NOTE: Untested, hypothetical...  Treat as PHP flavored pseudocode:

    class ChatMessage extends \Phpws\Core\Message {
        function __construct($text = '', \MyNamespace\ChatUser $sender, $channel) {
            $this->channel = $channel;
            $this->sender = $sender;
            parent::__construct($text, $channel->users);
        }

        public function send() {
            $data = array('sender' => $this->sender->getHandle(),
                'timestamp' => time(),
                'channel' => $this->channel->getName(),
            );
            $output = $this->frame(json_encode($data));
            foreach ($this->recipients as $recipient) {
                if ($recipient->getIsTlsUser()) {
                    $this->server->send($this->tls_frame($output, $recipient), $recipient);
                    continue;
                }
                $this->server->send($output, $recipient);
            }
        }
    }

**Comment by Xaraknid** [comment]
It's look like subprotocol it's good if you want to create your own subprotocol system but you should keep it on that level.  Implementing it on core level will probably cause some headache for coexisting  with other subprotocol like WAMP.  

here a list of some existing subprotocol working over websocket.
https://www.iana.org/assignments/websocket/websocket.xml
