### ISSUE TITLE
Cannot telnet to socketserver

### ISSUE THREAD

**Issue by DHNCarlos** [ghedipunk/PHP-Websockets#52]
Hi,

I have a question that is it possible for me to `telnet` to the newly started socket server to be able to test it from my terminal?

I currently set it up to listen on `127.0.0.1:21001` and when I try to telnet to it from another terminal it fails:
```
$ telnet 127.0.0.1:21001
telnet: 127.0.0.1:21001: Name or service not known
127.0.0.1:21001: Unknown host
$ telnet ws://127.0.0.1:21001
telnet: ws://127.0.0.1:21001: Name or service not known
```

Is it even possible to use `telnet` for WebSockets?

Thank-you in advance.

**Comment by DHNCarlos** [comment]
Very embarrasing of me. I forgot to open the port :)

Though now I'm behind another issue. I started up the WebSockets server and took the client JS code from this repo. When I load the page it starts connecting but then idles for around 4 minutes when finally timing out

```
WebSocket connection to 'ws://127.0.0.1:21001/' failed: WebSocket opening handshake timed out
```

**Comment by ghedipunk** [comment]
Closing old issue (I honestly feel bad for not at least responding to this).

For the record, telnet _can_ work with WebSocket connections, but involves writing binary data in the handshake, so is very difficult to do "by hand."

Suggestion: Use (or write) a client that handles the WebSocket protocol.
