### ISSUE TITLE
Send message to single user instead of all connected users

### ISSUE THREAD

**Issue by wasimmomin** [ghedipunk/PHP-Websockets#54]
I need an help to send an message to specific user instead of sending an message to all the connected users.Please help me to move on this right now i am stuck on this.

Thanks

Wasim Momin

**Comment by ghedipunk** [comment]
`$this->send($user,$message);` where $user extends the class WebSocketUser.

Closing because this is a support request, not a bug report.

Feel free to continue the conversation if you need additional help, as I'm not locking the conversation.
