### ISSUE TITLE
Unable to run in live server

### ISSUE THREAD

**Issue by meghawgt** [ghedipunk/PHP-Websockets#55]
Working fine in local sever.But when uploaded in live server,the server is running :

xxxx@xxxx [~/public_html]# php -q testwebsock.php
Server started
Listening on: 0.0.0.0:9006
Master socket: Resource id #6

but client.html giving error:
WebSocket - status 0
Disconnected - status 3

changed host in client page:

var host = "ws://xxx.com:9006/echobot"; // tried with site name
also 
var host = "ws://IP:9006/echobot"; // tried with IP too

but nothing is working.I am new with socket.So please let me know if I am missing anything.
Thanks in advance

**Comment by LGaitan** [comment]
Hi meghawgt,
make sure you've changed the settings in testwebsock.php and try,
```javascript
host = 'ws://xx.com:9006';
```

**Comment by meghawgt** [comment]
Hi @LGaitan 
in client.html page i changed the host :
var host = "ws://xxx.xx.xx.xxx:9006/echobot"; // SET THIS TO YOUR SERVER
and in testserver.php page :
$echo = new echoServer("xxx.xx.xx.xxx","9006");

still the same.

**Comment by Xaraknid** [comment]
on local server after :  Master socket: Resource id #6 
you start seeing this line each time you connect with new client :
Client connected #7
but didn't see it in liver server right ? 

first in testserver.php you can keep 0.0.0.0 unless you have multiple ip for the same server and only want to respond to ONLY one IP.

If you didn't see the  Client connected # line that mean the server never receive the request and most probably mean you didn't open the port on your firewall.
