### ISSUE TITLE
want to change response.

### ISSUE THREAD

**Issue by vinita90** [ghedipunk/PHP-Websockets#56]
Hey,
Code is working fine for me, what i am getting is the string in response which i am sending in request.
Now i want to change my response, how can i achieve this.

I hope it will make sense....

**Comment by Xaraknid** [comment]
change what you write in request, that will change the response.

Joking aside.

I guess what you want is creating something that do more than return what you write.  Check in testwebsock.php the method process().

**Comment by vinita90** [comment]
Okay, again i found solution, thank you for help Xaraknid :)
