### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jplevene** [ghedipunk/PHP-Websockets#61]
You state on the main page that you are trying to achieve a $250/mo Patreon reward level, why don't you add a link on the main page for donations via PayPal, etc.?  This might help reach the $250/m level sooner.

**Comment by ghedipunk** [comment]
Closing because it's not an issue...

But things along this line are in the back of my mind.

Next step is a documentation site.  That will have more options to allow others to support the project, from participation to donations and the like.

**Comment by jplevene** [comment]
The author of jsTree does donations by PayPal and earns quite well from 
it, thus the suggestion to help you out.

J

     `\|||/
      (O O)
__ooO_(_)_Ooo_____________________________________
_|_____|_____|_____|_____|_____|_____|_____|_____|
____|_____|_____|_____|_ From Justin Levene _|____
__oooO_|__Oooo ____|_____|_____|_____|_____|_____|
__(  )____(   )_|____|_____|_____|_____|_____|____
    \ (     ) /
     \_)   (_/

No trees were killed in the sending of this message...however a large number of electrons were terribly inconvenienced.
