### ISSUE TITLE
Not working on Mamp

### ISSUE THREAD

**Issue by irfanwv** [ghedipunk/PHP-Websockets#72]
I am using on MAMP, but it is not working. And also ws://192.168.0.115:3003/php give 

> This site can’t be reached.

How to it'll work.

**Comment by Xaraknid** [comment]
After a little search of what is MAMP.    

The websocket server MUST be executed as a command line also know as CLI.  Depending you using it under OSX or Windows. You'll need to do some step to enable php cli on mamp.  https://www.google.ca/?gws_rd=ssl#q=mamp+php+cli find the best option for you.

Also make sure you edit client.html line 20  to match your IP and only client.html should be available by the http server.

**Comment by ghedipunk** [comment]
Closing as this is not an issue with the server...  However, if you still need support, please feel free to continue to comment here.
