### ISSUE TITLE
How run it with SSL [wss]

### ISSUE THREAD

**Issue by johnson1823** [ghedipunk/PHP-Websockets#74]
Hey, I have server VPS with debian 6. I have installed PHP 5.6 with module openssl and I can't connect to the server with wss://. Do you know why ? Server respond timeout, but ws:// run.

**Comment by ghedipunk** [comment]
TLS is not currently implemented in the Master branch.

It is implemented in the Legacy branch, though.  See: https://github.com/ghedipunk/PHP-Websockets/tree/legacy

As it is currently implemented, you will need to run two separate instances of the server if you want to have both WS and WSS running at the same time.  Also note that you _should_ have two separate instances of any server running, to help prevent leaking secure data over an insecure connection.

Closing as a "wontfix" as there is already active development on the new development branches that will have TLS support, and the legacy branch provides a mostly compatible alternative to the master branch.  Thus there will be no code changes specific to this issue.

If you need more support, please feel free to continue to comment here despite the issue being closed.

**Comment by amaretto4u** [comment]
It's better to use apache or nginx to handle ssl connections and forward it to websockets
Way to forward connection thought nginx :
```
upstream websocket {
    server 127.0.0.1:8001;
}
server {
   ...
   location /socket {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 600s;
    }
   ...
}
```
change 8001 to your port

**Comment by johnson1823** [comment]
Ghedipunk I use it and configure, but I heve error:
failed: Error during WebSocket handshake: Unexpected response code: 405

**Comment by jeancaffou** [comment]
@amaretto4u wouldn't this put unnecessary strain on the webserver, specifically the MaxClients directive?

**Comment by amaretto4u** [comment]
I think it depends on active user count, but i don't have problem on my setups.
I use this combination more than 2 years. Don't have any notable difference in memory or CPU consumption if i turn it on or off.

**Comment by jeancaffou** [comment]
How many peak active users?

**Comment by amaretto4u** [comment]
host have ~100 domains
~700 peak active connections
~100 of them with web sockets
