### ISSUE TITLE
Segmentation fault (core dumped) in Ubuntu server

### ISSUE THREAD

**Issue by emman-ok** [ghedipunk/PHP-Websockets#78]
Am getting this when i start the server.
Server started
Listening on: 5.152.179.147:8080
Master socket: Resource id #8
Segmentation fault (core dumped)

then the client application cannot connect to the system.

**Comment by Xaraknid** [comment]
I'll make assumptions that did not happens at the start but after some client connect to the server, if not tell us.

In short you running out of memory.

**Comment by ghedipunk** [comment]
PHP programs themselves can't segfault: There is no direct memory pointer management, so no way for the scripts to attempt to read from or write to an inaccessible memory location.

There is likely a bug in your version of PHP or in an extension loaded in your server.  Please upgrade to the latest version in the PHP branch that supports your code base  (I suggest PHP 7.0.6, but this may not be available to you.  At a minimum, you should be running either 5.6.21 or 5.5.35), and recompile any extensions that are not managed by your distro.

**Comment by emman-ok** [comment]
Am using php 7.0.5 and i don't think am running out of memory.

**Comment by emman-ok** [comment]
Problem Solved. Segmentation fault (core dumped) is caused by mysqli library that am using. Thanks.
