### ISSUE TITLE
#!/usr/bin/env php Failed: socket_bind()

### ISSUE THREAD

**Issue by tqkiettk10** [ghedipunk/PHP-Websockets#79]
Hello, I new bie with php develop, I try to use ghedipunk Websockets with local host work fine with default server 0.0.0.0 port 9000 and client connect to 127.0.0.1:9000/something. But when I upload it to hosting it donot work, I try use this host and my host, change port, change port lager 40000 but it donot work. 
Another question is my host dont have cmd, so i can't run websocket, I try to test websocket with goto server.php link on browser, have any way?
I searching for 6h but cannot fix it.
Any help, Please!
Sorry with my bad english.

**Comment by ghedipunk** [comment]
Your hosting provider seems to have turned off the ability for programs that they haven't authorized to create a socket.

This is a security feature, to protect the other users of the server.

Either change your hosting plan to one that allows creating sockets, or find a different hosting provider who does.
