### ISSUE TITLE
websocket lunch on remote host 

### ISSUE THREAD

**Issue by mkeyno** [ghedipunk/PHP-Websockets#92]
hi, I'm sorry to open ticket for my question , but actually I'm not pro in php and with your instruction not figure out how to install it in my remote directory host , and really appreciate for couple of hints , in fact I've tried to hook url on my host to the Telegram webhoock call back bot, so at first step new update data inserted to MySQL database then websoket server give the update data to designated live client .
can you tell me which files should be copy in designated host URL and what files should be modified?
Thanks

**Comment by ghedipunk** [comment]
You don't.  These files should not be accessible directly through a URL.  They open up a non-web port on your server after being executed like other server software.

You need shell access to your server.  You need to understand what all of that means first.
