### ISSUE TITLE
is there any way to keep connection across pages?

### ISSUE THREAD

**Issue by petrospap** [ghedipunk/PHP-Websockets#93]
Hello 
any idea how to keep connection across pages or on reload?

**Comment by ghedipunk** [comment]
You can not keep the connection open across different pages or when reloading the page.

Rather, use client side code to set a cookie with some sort of session token and, when reconnecting, read that token.

It's dangerous to use sessions alone. Take this! https://www.owasp.org/index.php/Session_Management_Cheat_Sheet

**Comment by petrospap** [comment]
Thank you ghedipunk, although I don't understand what kind of session/cookie must store  
Can you please provide some information??


I spend lot of time reading to find out how to make a persist connection
I find this 
https://github.com/joewalnes/reconnecting-websocket

or with iframe 
https://html.spec.whatwg.org/multipage/comms.html#introduction-12

SharedWorker might be a good idea but not all browsers support it.

Also i try to read why connection lost when you go to another page/reload but I can't find any information to explain..

**Comment by petrospap** [comment]
OK I read the websocket protocol
https://tools.ietf.org/html/rfc6455#section-1.3
This answered to my question :)
