### ISSUE TITLE
how can i change user id when doHandshake establish

### ISSUE THREAD

**Issue by petrospap** [ghedipunk/PHP-Websockets#95]
Hello

I connect like this ws://127.0.0.1:9000/5

in function doHandshake we got the /5  from headers

how can i change $user->id to existing uniqid('u') + /5

**Comment by lgaitan** [comment]
Maybe you could change the user class

**Comment by petrospap** [comment]
okie I found it :)
At the end of function doHandshake
```
// added new line
$user->id = $user->id.$user->requestedResource;
// end new line
$this->connected($user);
```

Thanks!

**Comment by petrospap** [comment]
OK I reopen this issue
by adding $user->id = $user->id.$user->requestedResource;
seems that is working i.e  $id have changed
but this is not the right way
when I reload the page seems like socket not closed properly

The changes i have made is 

1) in function doHandshake at the end

```
$user->id = $user->id.$user->requestedResource;
 $this->connected($user);
//$this->stderr(print_r($user));
```
2) on function connected I have added
```
	foreach ($this->users as $all) {
		$totalAll[] = $all;
		$this->send($all, 'hi');
		$this->stderr('user connected and say to all "hi"');
	}
	
	$total = count($totalAll);
	$this->stderr('total users = '.$total);
```

This is the results when I connect and after when I reload page

```
Please close this command only for Shutdown
server websocket is starting ...
Server started
Listening on: 0.0.0.0:9000
Master socket: Resource id #6
Client connected. Resource id #7
user connected and say to all "hi"
total users = 1
Client disconnected. Resource id #7
Client connected. Resource id #8
user connected and say to all "hi"
user connected and say to all "hi"
total users = 2
```

is there any way to change properly the id?

**Comment by lgaitan** [comment]
Every client has a instance of the WebSocketUser class, modify the class to include your own id

**Comment by petrospap** [comment]
Hello lgaitan can you give any small example of how can I do this (if is something easy)

**Comment by lgaitan** [comment]
Just change the users.php file, inside the __construct function

```php
function __construct($id, $socket) {
    $this->myId = SOMETHING;
}
```

then, access it as $user->myId

**Comment by petrospap** [comment]
Thanks I'll try it!

**Comment by ghedipunk** [comment]
Create your own WebSocketUser class that inherits, and add your own ID.

file `myUser.php`

    <?php
    class MyUser extends WebSocketUser {
    
        public $myId;

        function __construct($id, $socket, $myId) {
            parent::__construct($id, $socket);
            $this->myId = $myId;
        }
    }

**Comment by petrospap** [comment]
Thank YOU all :))
