### ISSUE TITLE
Use php multi-threading in a web socket server

### ISSUE THREAD

**Issue by fazelit** [ghedipunk/PHP-Websockets#96]
How Use php multi-threading in a web socket server?

**Comment by ghedipunk** [comment]
The go-to for all PHP threading is pthreads. http://php.net/manual/en/book.pthreads.php

I do not have any plans to support threading.  You are, of course, free to develop your own threaded version yourself, with my blessing.

**Comment by fazelit** [comment]
> The go-to for all PHP threading is pthreads. http://php.net/manual/en/book.pthreads.php

>  do not have any plans to support threading. You are, of course, free to develop your own threaded version yourself, with my blessing.

How Use Multi thread in class PHP-Websockets?
Explain along with examples.
Thanks

**Comment by ghedipunk** [comment]
Spend a few hours reading this:  http://www.catb.org/esr/faqs/smart-questions.html

Then spend a few months learning the basics of threading in languages that are known to provide robust support for threading.

Then spend a few days developing applications in PHP using pthreads.

THEN come back here and ask questions that show that you have done the bare minimum required to understand what it is you're asking in the first place.
